name: Jest CI
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Jest
        uses: stefanoeb/jest-action@1.0.4
        with:
          jestArgs: ../../app
