name: Jest CI
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change directory
        run: cd app 
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        run: npm run test
