name: Jest CI
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        run: npm run test
      - name: Jest Reporter
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: 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
          test-command: "npm run test --coverage"

