name: Jest CI
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change directory
        run: cd app 
      - name: Install dependencies
        uses: npm install
      - name: Run Jest
        uses: npm run test
